# node modules in executable path
PATH := node_modules/.bin:$(PATH)

# OSX requires this variable exported so that PATH is also exported.
SHELL := /bin/bash

JS_SRC = $(shell find . -type f -name '*.js' ! -path './node_modules/*')
JSON_SRC = $(shell find . -type f -name '*.json' ! -path './node_modules/*')

.PHONY: lint test

lint:
	jsonlint -q -c ${JSON_SRC}
	eslint ${JS_SRC} ${ESLINT_ARGS}

test:
	# PGDB_TCP_PORT=5432
	# PGDB_TCP_HOST=127.0.0.1
	# PGDB_USER=riddhi
	# PGDB_DB=twitter
	PGDB_DB=testdb mocha

